apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: golang-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: golang-test
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - golang-test
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - golang-test
            topologyKey: kubernetes.io/hostname
      containers:
      - image: golang-test
        name: golang-test
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "15Mi"
            cpu: "100m"
