apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: golang-test
  name: golang-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: golang-test
  sessionAffinity: None
  type: ClusterIP
